twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ["bootstrap_4_layout.html.twig"]
    # globals: 
        # ga-tracking: 'UA-xxxxxxxxx'
    paths: 
        '%kernel.project_dir%/public/img': images


when@test:
    twig:
        strict_variables: true

